name: clang-format check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  formatting-check:
    name: Formatting Check of ${{ github.workspace }}/${{ matrix.path }} directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '19'
          check-path: ${{ github.workspace }}
